export const bookStores = [
  {
    id: 1,
    owner: "Mekdi",
    location: "Addis Ababa",
    rating: 4.5,
    website: "www.addislibrary.com",
    description: "",
    imageUrl: "",
    mapEmbed:
      "https://maps.google.com/maps?q=shop&t=&z=13&ie=UTF8&iwloc=&output=embed",
    phone: "555-0123",
    email: "shop@example.com",
    name: "ADDIS LIBRARY",
    contact: "Office: +25111467...",
  },
  {
    id: 2,
    owner: "miki",
    location: "Addis Ababa",
    rating: 4.5,
    website: "www.africabookstore.com",
    description: "",
    imageUrl: "",
    mapEmbed:
      "https://maps.google.com/maps?q=shop&t=&z=13&ie=UTF8&iwloc=&output=embed",
    phone: "555-0123",
    email: "shop@example.com",
    name: "AFRICA BOOK STORE",
    contact: "Office: +25111111...",
  },
  {
    id: 3,
    owner: "sami",
    location: "Addis Ababa",
    rating: 4.5,
    website: "www.africanbookshop.com",
    description: "",
    imageUrl: "",
    mapEmbed:
      "https://maps.google.com/maps?q=shop&t=&z=13&ie=UTF8&iwloc=&output=embed",
    phone: "555-0123",
    email: "shop@example.com",
    name: "AFRICAN BOOK SHOP",
    contact: "Office: +25111111...",
  },
  {
    id: 4,
    owner: "aggam",
    location: "Addis Ababa",
    rating: 4.5,
    website: "www.aggam.com",
    description: "",
    imageUrl: "",
    mapEmbed:
      "https://maps.google.com/maps?q=shop&t=&z=13&ie=UTF8&iwloc=&output=embed",
    phone: "555-0123",
    email: "shop@example.com",
    name: "AGGAM HEALTH, NUTRITION, CHILD CARE AND MARRIAGE COUNSELING",
    contact: "Mobile: +25191167...",
  },
  {
    id: 5,
    owner: "Fasika",
    location: "Addis Ababa",
    rating: 4.5,
    website: "www.al-aqssa.com",
    description: "",
    imageUrl: "",
    mapEmbed:
      "https://maps.google.com/maps?q=shop&t=&z=13&ie=UTF8&iwloc=&output=embed",
    phone: "555-0123",
    email: "shop@example.com",
    name: "AL-AQSSA BOOK STORE",
    contact: "Office: +25111111...",
  },
  {
    id: 6,
    owner: "ayana",
    location: "Addis Ababa",
    rating: 4.5,
    website: "www.ayanapublishing.com",
    description: "",
    imageUrl: "",
    mapEmbed:
      "https://maps.google.com/maps?q=shop&t=&z=13&ie=UTF8&iwloc=&output=embed",
    phone: "555-0123",
    email: "shop@example.com",
    name: "AYANA PUBLISHING P.L.C",
    contact: "Mobile: +25191194...",
  },
  {
    id: 7,
    owner: "Bisre",
    location: "Addis Ababa",
    rating: 4.5,
    website: "www.aynalem.com",
    description: "",
    imageUrl: "",
    mapEmbed:
      "https://maps.google.com/maps?q=shop&t=&z=13&ie=UTF8&iwloc=&output=embed",
    phone: "555-0123",
    email: "shop@example.com",
    name: "AYNALEM BOOK STORE",
    contact: "Office: +25111550...",
  },
];
